services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GOOGLE_APPLICATION_CREDENTIALS=/code/secrets/googlecloud_api_key.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
  api_docks:
    image: swaggerapi/swagger-ui
    volumes:
      - ${PWD}/schema.yml:/schema.yml
    environment:
      - SWAGGER_JSON=/schema.yml
    ports:
      - 80:8080