# Generated by Django 5.0.1 on 2024-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
