# Generated by Django 5.0.1 on 2024-01-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='file',
        ),
    ]
